name: "Setup project"
runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v2
    with:
      node-version: 17
      cache: 'yarn'
  - if: runner.os == 'macOS'
    run: brew install wabt boost
    shell: bash
  - if: runner.os == 'Linux'
    run: sudo apt-get install libboost-dev libboost-filesystem-dev libboost-program-options-dev
    shell: bash
  - if: runner.os == 'Linux'
    run: |
      curl -L -s https://github.com/WebAssembly/wabt/releases/download/1.0.30/wabt-1.0.30-ubuntu.tar.gz | tar xvz -C /tmp
      sudo mv /tmp/wabt-1.0.30/bin/* /usr/local/bin
      sudo mv /tmp/wabt-1.0.30/include/* /usr/local/include
      sudo mv /tmp/wabt-1.0.30/lib/*.a /usr/local/lib
    shell: bash
  - if: runner.os == 'Windows'
    run: |
      curl -L -s https://github.com/WebAssembly/wabt/releases/download/1.0.30/wabt-1.0.30-windows.tar.gz | tar xvz -C /tmp
      mv /tmp/wabt-1.0.30 /c/tools/wabt
      cp /c/tools/wabt/bin/* /c/Windows/system32
    shell: bash
  - if: runner.os == 'Windows'
    run: |
      C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-boost
    shell: cmd
  - run: yarnpkg --pure-lockfile
    shell: bash
