name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarnpkg build
      - run: make -C src/web/notebook
      - run: yarnpkg lint
      - run: yarnpkg test --coverage
