name: Build Standalone

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  publish-standalone:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: make -C src/standalone install-deps all