name: Publish Standalone

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-standalone:
    needs: build
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: make -C src/standalone install-deps package
      - uses: AButler/upload-release-assets@e940f6342206c9655b12a28a79646d3982571ad9
        with:
          files: 'src/standalone/waforth-*.tgz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
