name: Publish Release

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarnpkg publish --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
